### ISSUE TITLE
Raise readable errors when inputting alphabets

### ISSUE THREAD

**Issue by vivekkartha** [ajinjude/seven_segment#1]
Right now encoding an alphabet raises the following error trace:
`Traceback (most recent call last):
        6: from /usr/bin/irb:11:in `<main>'
        5: from (irb):5
        4: from /var/lib/gems/2.5.0/gems/seven_segment-0.1.0/lib/seven_segment.rb:29:in `encode'
        3: from /var/lib/gems/2.5.0/gems/seven_segment-0.1.0/lib/seven_segment.rb:24:in `to_segment'
        2: from /var/lib/gems/2.5.0/gems/seven_segment-0.1.0/lib/seven_segment.rb:24:in `map'
        1: from /var/lib/gems/2.5.0/gems/seven_segment-0.1.0/lib/seven_segment.rb:24:in `block in to_segment'
NoMethodError (undefined method `scan' for nil:NilClass)`
Display a better error

**Comment by ajinjude** [comment]
More readable errors are introduced in version 0.1.1 of the gem. See commit: c68f8854859d1e2a85322c1557fdfb09eb5f17de

**Comment by vivekkartha** [comment]
Checked and confirmed, closing the issue. Thanks.
